apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-deployment
  namespace: default
  labels:
    app: warehouse-deployment
spec:
  selector:
    matchLabels:
      app: warehouse-deployment
  template:
    metadata:
      labels:
        app: warehouse-deployment
    spec:
      containers:
        - name: warehouse-service
          image: asia-southeast2-docker.pkg.dev/wandika-project/com-multiwarehouse-e-commerce-repository/warehouse.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres?currentSchema=warehouse&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: SPRING_DATASOURCE_INITIALIZATION-MODE
              value: "never"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry:8081"warehouse-service-deployment.yml
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
  namespace: default
  labels:
    app: warehouse-service
spec:
  selector:
    app: warehouse-deployment
  ports:
    - name: warehouse-service-port
      protocol: TCP
      port: 80
      targetPort: 8181
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: warehouse-deployment-hpa
  namespace: default
  labels:
    app: warehouse-deployment
spec:
  scaleTargetRef:
    kind: Deployment
    name: warehouse-deployment
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 85
